# Name of configuration
name = PropertiesConfig

# File location
property.filename = logs

# Appenders
appenders = console, file, errorFile

# Loggers list
loggers = baseclass, poi, opc, testng, utils

# Console Appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# File Appender (Captures all logs into mylog.log & resets on startup)
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = ${filename}/mylog.log
appender.file.append = false
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# Error File Appender (Captures only ERROR logs into error.log & resets on startup)
appender.errorFile.type = File
appender.errorFile.name = ERRORLOGFILE
appender.errorFile.fileName = ${filename}/error.log
appender.errorFile.append = false
appender.errorFile.layout.type = PatternLayout
appender.errorFile.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.errorFile.filter.threshold.type = ThresholdFilter
appender.errorFile.filter.threshold.level = error 
appender.errorFile.filter.threshold.onMatch = ACCEPT
appender.errorFile.filter.threshold.onMismatch = DENY

# Logger for BaseClass
logger.baseclass.name = com.bci.wms.base.BaseClass
logger.baseclass.level = debug
logger.baseclass.additivity = false
logger.baseclass.appenderRefs = file, errorFile, stdout
logger.baseclass.appenderRef.file.ref = LOGFILE
logger.baseclass.appenderRef.errorFile.ref = ERRORLOGFILE
logger.baseclass.appenderRef.stdout.ref = STDOUT

# Root Logger (all other logs)
rootLogger.level = debug
rootLogger.appenderRefs = console, file, errorFile
rootLogger.appenderRef.console.ref = STDOUT
rootLogger.appenderRef.file.ref = LOGFILE
rootLogger.appenderRef.errorFile.ref = ERRORLOGFILE

# Turn off Apache POI debug logs
logger.poi.name = org.apache.poi
logger.poi.level = error

# Turn off OPC (XML relationships)
logger.opc.name = org.apache.poi.openxml4j
logger.opc.level = error

# Turn off TestNG internal logs
logger.testng.name = org.testng
logger.testng.level = warn
logger.testng.additivity = false
logger.testng.appenderRefs = stdout
logger.testng.appenderRef.stdout.ref = STDOUT

# Turn off TestNG Utils logs
logger.utils.name = Utils
logger.utils.level = warn
logger.utils.additivity = false
logger.utils.appenderRefs = stdout
logger.utils.appenderRef.stdout.ref = STDOUT